// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.3
// source: grpc-proto/media.proto

package grpc_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PING
type PingApiMediaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingApiMediaRequest) Reset() {
	*x = PingApiMediaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_media_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingApiMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingApiMediaRequest) ProtoMessage() {}

func (x *PingApiMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_media_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingApiMediaRequest.ProtoReflect.Descriptor instead.
func (*PingApiMediaRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_media_proto_rawDescGZIP(), []int{0}
}

type PingApiMediaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *PingApiMediaResponse) Reset() {
	*x = PingApiMediaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_media_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingApiMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingApiMediaResponse) ProtoMessage() {}

func (x *PingApiMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_media_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingApiMediaResponse.ProtoReflect.Descriptor instead.
func (*PingApiMediaResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_media_proto_rawDescGZIP(), []int{1}
}

func (x *PingApiMediaResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// POST MEDIA
type PostUploadMediaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId           string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserEmail        string `protobuf:"bytes,2,opt,name=userEmail,proto3" json:"userEmail,omitempty"`
	IsVirtual        bool   `protobuf:"varint,3,opt,name=isVirtual,proto3" json:"isVirtual,omitempty"`
	PostId           string `protobuf:"bytes,4,opt,name=postId,proto3" json:"postId,omitempty"`
	MimeType         string `protobuf:"bytes,5,opt,name=mimeType,proto3" json:"mimeType,omitempty"`
	OriginalFilename string `protobuf:"bytes,6,opt,name=originalFilename,proto3" json:"originalFilename,omitempty"`
	SizeCategory     string `protobuf:"bytes,7,opt,name=sizeCategory,proto3" json:"sizeCategory,omitempty"`
	Photo            []byte `protobuf:"bytes,8,opt,name=photo,proto3" json:"photo,omitempty"`
}

func (x *PostUploadMediaRequest) Reset() {
	*x = PostUploadMediaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_media_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostUploadMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUploadMediaRequest) ProtoMessage() {}

func (x *PostUploadMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_media_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUploadMediaRequest.ProtoReflect.Descriptor instead.
func (*PostUploadMediaRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_media_proto_rawDescGZIP(), []int{2}
}

func (x *PostUploadMediaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PostUploadMediaRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *PostUploadMediaRequest) GetIsVirtual() bool {
	if x != nil {
		return x.IsVirtual
	}
	return false
}

func (x *PostUploadMediaRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *PostUploadMediaRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *PostUploadMediaRequest) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

func (x *PostUploadMediaRequest) GetSizeCategory() string {
	if x != nil {
		return x.SizeCategory
	}
	return ""
}

func (x *PostUploadMediaRequest) GetPhoto() []byte {
	if x != nil {
		return x.Photo
	}
	return nil
}

type PostUploadMediaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Media *Media `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
}

func (x *PostUploadMediaResponse) Reset() {
	*x = PostUploadMediaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_media_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostUploadMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUploadMediaResponse) ProtoMessage() {}

func (x *PostUploadMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_media_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUploadMediaResponse.ProtoReflect.Descriptor instead.
func (*PostUploadMediaResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_media_proto_rawDescGZIP(), []int{3}
}

func (x *PostUploadMediaResponse) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

// FETCH ONE POST MEDIA
type PostFetchMediaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	IsVirtual bool   `protobuf:"varint,2,opt,name=isVirtual,proto3" json:"isVirtual,omitempty"`
}

func (x *PostFetchMediaRequest) Reset() {
	*x = PostFetchMediaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_media_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostFetchMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostFetchMediaRequest) ProtoMessage() {}

func (x *PostFetchMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_media_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostFetchMediaRequest.ProtoReflect.Descriptor instead.
func (*PostFetchMediaRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_media_proto_rawDescGZIP(), []int{4}
}

func (x *PostFetchMediaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PostFetchMediaRequest) GetIsVirtual() bool {
	if x != nil {
		return x.IsVirtual
	}
	return false
}

type PostFetchMediaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhotoObjects []*Media `protobuf:"bytes,1,rep,name=photoObjects,proto3" json:"photoObjects,omitempty"`
}

func (x *PostFetchMediaResponse) Reset() {
	*x = PostFetchMediaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_media_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostFetchMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostFetchMediaResponse) ProtoMessage() {}

func (x *PostFetchMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_media_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostFetchMediaResponse.ProtoReflect.Descriptor instead.
func (*PostFetchMediaResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_media_proto_rawDescGZIP(), []int{5}
}

func (x *PostFetchMediaResponse) GetPhotoObjects() []*Media {
	if x != nil {
		return x.PhotoObjects
	}
	return nil
}

// FETCH MORE THAN ONE POST MEDIA
type PostsFetchMediaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostIds   []string `protobuf:"bytes,1,rep,name=postIds,proto3" json:"postIds,omitempty"`
	IsVirtual bool     `protobuf:"varint,2,opt,name=isVirtual,proto3" json:"isVirtual,omitempty"`
}

func (x *PostsFetchMediaRequest) Reset() {
	*x = PostsFetchMediaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_media_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostsFetchMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostsFetchMediaRequest) ProtoMessage() {}

func (x *PostsFetchMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_media_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostsFetchMediaRequest.ProtoReflect.Descriptor instead.
func (*PostsFetchMediaRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_media_proto_rawDescGZIP(), []int{6}
}

func (x *PostsFetchMediaRequest) GetPostIds() []string {
	if x != nil {
		return x.PostIds
	}
	return nil
}

func (x *PostsFetchMediaRequest) GetIsVirtual() bool {
	if x != nil {
		return x.IsVirtual
	}
	return false
}

type PostsFetchMediaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MediaObjects []*Media `protobuf:"bytes,1,rep,name=mediaObjects,proto3" json:"mediaObjects,omitempty"`
}

func (x *PostsFetchMediaResponse) Reset() {
	*x = PostsFetchMediaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_media_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostsFetchMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostsFetchMediaResponse) ProtoMessage() {}

func (x *PostsFetchMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_media_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostsFetchMediaResponse.ProtoReflect.Descriptor instead.
func (*PostsFetchMediaResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_media_proto_rawDescGZIP(), []int{7}
}

func (x *PostsFetchMediaResponse) GetMediaObjects() []*Media {
	if x != nil {
		return x.MediaObjects
	}
	return nil
}

// DELETE MEDIA
type PostDeleteMediaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId    string `protobuf:"bytes,1,opt,name=postId,proto3" json:"postId,omitempty"`
	IsVirtual bool   `protobuf:"varint,2,opt,name=isVirtual,proto3" json:"isVirtual,omitempty"`
}

func (x *PostDeleteMediaRequest) Reset() {
	*x = PostDeleteMediaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_media_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostDeleteMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDeleteMediaRequest) ProtoMessage() {}

func (x *PostDeleteMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_media_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDeleteMediaRequest.ProtoReflect.Descriptor instead.
func (*PostDeleteMediaRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_media_proto_rawDescGZIP(), []int{8}
}

func (x *PostDeleteMediaRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *PostDeleteMediaRequest) GetIsVirtual() bool {
	if x != nil {
		return x.IsVirtual
	}
	return false
}

type PostDeleteMediaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *PostDeleteMediaResponse) Reset() {
	*x = PostDeleteMediaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_media_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostDeleteMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDeleteMediaResponse) ProtoMessage() {}

func (x *PostDeleteMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_media_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDeleteMediaResponse.ProtoReflect.Descriptor instead.
func (*PostDeleteMediaResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_media_proto_rawDescGZIP(), []int{9}
}

func (x *PostDeleteMediaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// THE PHOTO
type Media struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp     string `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UserId        string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	IsVirtual     bool   `protobuf:"varint,3,opt,name=isVirtual,proto3" json:"isVirtual,omitempty"`
	PostId        string `protobuf:"bytes,4,opt,name=postId,proto3" json:"postId,omitempty"`
	MediaId       string `protobuf:"bytes,5,opt,name=mediaId,proto3" json:"mediaId,omitempty"`
	MediaType     string `protobuf:"bytes,6,opt,name=mediaType,proto3" json:"mediaType,omitempty"`
	MediaFilename string `protobuf:"bytes,7,opt,name=mediaFilename,proto3" json:"mediaFilename,omitempty"`
	CoverFilename string `protobuf:"bytes,8,opt,name=coverFilename,proto3" json:"coverFilename,omitempty"`
	Metadata      string `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *Media) Reset() {
	*x = Media{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_media_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_media_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_grpc_proto_media_proto_rawDescGZIP(), []int{10}
}

func (x *Media) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Media) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Media) GetIsVirtual() bool {
	if x != nil {
		return x.IsVirtual
	}
	return false
}

func (x *Media) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *Media) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *Media) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *Media) GetMediaFilename() string {
	if x != nil {
		return x.MediaFilename
	}
	return ""
}

func (x *Media) GetCoverFilename() string {
	if x != nil {
		return x.CoverFilename
	}
	return ""
}

func (x *Media) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

var File_grpc_proto_media_proto protoreflect.FileDescriptor

var file_grpc_proto_media_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x64,
	0x69, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x22,
	0x15, 0x0a, 0x13, 0x50, 0x69, 0x6e, 0x67, 0x41, 0x70, 0x69, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2e, 0x0a, 0x14, 0x50, 0x69, 0x6e, 0x67, 0x41, 0x70,
	0x69, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x86, 0x02, 0x0a, 0x16, 0x50, 0x6f, 0x73, 0x74, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65,
	0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73,
	0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x56, 0x69, 0x72,
	0x74, 0x75, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x56, 0x69,
	0x72, 0x74, 0x75, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x6d, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6d, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x6f, 0x72, 0x69,
	0x67, 0x69, 0x6e, 0x61, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x10, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x46, 0x69, 0x6c,
	0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x69, 0x7a, 0x65, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x69, 0x7a,
	0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f,
	0x74, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x22,
	0x3d, 0x0a, 0x17, 0x50, 0x6f, 0x73, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x64,
	0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x6d, 0x65,
	0x64, 0x69, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x65, 0x64, 0x69,
	0x61, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x05, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x22, 0x4d,
	0x0a, 0x15, 0x50, 0x6f, 0x73, 0x74, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4d, 0x65, 0x64, 0x69, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x69, 0x73, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x22, 0x4a, 0x0a,
	0x16, 0x50, 0x6f, 0x73, 0x74, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x74, 0x6f,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x0c, 0x70, 0x68, 0x6f,
	0x74, 0x6f, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x22, 0x50, 0x0a, 0x16, 0x50, 0x6f, 0x73,
	0x74, 0x73, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x69, 0x73, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x69, 0x73, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x22, 0x4b, 0x0a, 0x17, 0x50,
	0x6f, 0x73, 0x74, 0x73, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x0c, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d,
	0x65, 0x64, 0x69, 0x61, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x0c, 0x6d, 0x65, 0x64, 0x69,
	0x61, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x22, 0x4e, 0x0a, 0x16, 0x50, 0x6f, 0x73, 0x74,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73,
	0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69,
	0x73, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x22, 0x33, 0x0a, 0x17, 0x50, 0x6f, 0x73, 0x74,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x93, 0x02,
	0x0a, 0x05, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x69, 0x73, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x69, 0x73, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x73,
	0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x49, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x6d,
	0x65, 0x64, 0x69, 0x61, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x46,
	0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x32, 0x9c, 0x03, 0x0a, 0x0c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x41, 0x70, 0x69, 0x4d,
	0x65, 0x64, 0x69, 0x61, 0x12, 0x1a, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x50, 0x69, 0x6e,
	0x67, 0x41, 0x70, 0x69, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x41, 0x70, 0x69,
	0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a,
	0x0f, 0x50, 0x6f, 0x73, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x64, 0x69, 0x61,
	0x12, 0x1d, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4d, 0x0a, 0x0e, 0x50, 0x6f, 0x73, 0x74, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4d, 0x65, 0x64, 0x69,
	0x61, 0x12, 0x1c, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50,
	0x0a, 0x0f, 0x50, 0x6f, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69,
	0x61, 0x12, 0x1d, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x50, 0x0a, 0x0f, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4d, 0x65,
	0x64, 0x69, 0x61, 0x12, 0x1d, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x50, 0x6f, 0x73, 0x74,
	0x73, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x73,
	0x46, 0x65, 0x74, 0x63, 0x68, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x18, 0x5a, 0x16, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_proto_media_proto_rawDescOnce sync.Once
	file_grpc_proto_media_proto_rawDescData = file_grpc_proto_media_proto_rawDesc
)

func file_grpc_proto_media_proto_rawDescGZIP() []byte {
	file_grpc_proto_media_proto_rawDescOnce.Do(func() {
		file_grpc_proto_media_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_proto_media_proto_rawDescData)
	})
	return file_grpc_proto_media_proto_rawDescData
}

var file_grpc_proto_media_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_grpc_proto_media_proto_goTypes = []interface{}{
	(*PingApiMediaRequest)(nil),     // 0: media.PingApiMediaRequest
	(*PingApiMediaResponse)(nil),    // 1: media.PingApiMediaResponse
	(*PostUploadMediaRequest)(nil),  // 2: media.PostUploadMediaRequest
	(*PostUploadMediaResponse)(nil), // 3: media.PostUploadMediaResponse
	(*PostFetchMediaRequest)(nil),   // 4: media.PostFetchMediaRequest
	(*PostFetchMediaResponse)(nil),  // 5: media.PostFetchMediaResponse
	(*PostsFetchMediaRequest)(nil),  // 6: media.PostsFetchMediaRequest
	(*PostsFetchMediaResponse)(nil), // 7: media.PostsFetchMediaResponse
	(*PostDeleteMediaRequest)(nil),  // 8: media.PostDeleteMediaRequest
	(*PostDeleteMediaResponse)(nil), // 9: media.PostDeleteMediaResponse
	(*Media)(nil),                   // 10: media.Media
}
var file_grpc_proto_media_proto_depIdxs = []int32{
	10, // 0: media.PostUploadMediaResponse.media:type_name -> media.Media
	10, // 1: media.PostFetchMediaResponse.photoObjects:type_name -> media.Media
	10, // 2: media.PostsFetchMediaResponse.mediaObjects:type_name -> media.Media
	0,  // 3: media.MediaService.PingApiMedia:input_type -> media.PingApiMediaRequest
	2,  // 4: media.MediaService.PostUploadMedia:input_type -> media.PostUploadMediaRequest
	4,  // 5: media.MediaService.PostFetchMedia:input_type -> media.PostFetchMediaRequest
	8,  // 6: media.MediaService.PostDeleteMedia:input_type -> media.PostDeleteMediaRequest
	6,  // 7: media.MediaService.PostsFetchMedia:input_type -> media.PostsFetchMediaRequest
	1,  // 8: media.MediaService.PingApiMedia:output_type -> media.PingApiMediaResponse
	3,  // 9: media.MediaService.PostUploadMedia:output_type -> media.PostUploadMediaResponse
	5,  // 10: media.MediaService.PostFetchMedia:output_type -> media.PostFetchMediaResponse
	9,  // 11: media.MediaService.PostDeleteMedia:output_type -> media.PostDeleteMediaResponse
	7,  // 12: media.MediaService.PostsFetchMedia:output_type -> media.PostsFetchMediaResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_grpc_proto_media_proto_init() }
func file_grpc_proto_media_proto_init() {
	if File_grpc_proto_media_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_proto_media_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingApiMediaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_media_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingApiMediaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_media_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostUploadMediaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_media_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostUploadMediaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_media_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostFetchMediaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_media_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostFetchMediaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_media_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostsFetchMediaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_media_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostsFetchMediaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_media_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostDeleteMediaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_media_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostDeleteMediaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_media_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Media); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_proto_media_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_media_proto_goTypes,
		DependencyIndexes: file_grpc_proto_media_proto_depIdxs,
		MessageInfos:      file_grpc_proto_media_proto_msgTypes,
	}.Build()
	File_grpc_proto_media_proto = out.File
	file_grpc_proto_media_proto_rawDesc = nil
	file_grpc_proto_media_proto_goTypes = nil
	file_grpc_proto_media_proto_depIdxs = nil
}
