// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.3
// source: grpc-proto/message.proto

package grpc_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MessageService_PingApiMessage_FullMethodName      = "/message.MessageService/PingApiMessage"
	MessageService_CustomerMessage_FullMethodName     = "/message.MessageService/CustomerMessage"
	MessageService_ChatbotMessage_FullMethodName      = "/message.MessageService/ChatbotMessage"
	MessageService_PingTasksQueue_FullMethodName      = "/message.MessageService/PingTasksQueue"
	MessageService_CreateTaskMessage_FullMethodName   = "/message.MessageService/CreateTaskMessage"
	MessageService_CompleteTaskMessage_FullMethodName = "/message.MessageService/CompleteTaskMessage"
)

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageServiceClient interface {
	PingApiMessage(ctx context.Context, in *PingApiMessageRequest, opts ...grpc.CallOption) (*PingApiMessageResponse, error)
	CustomerMessage(ctx context.Context, in *CustomerMessageRequest, opts ...grpc.CallOption) (*CustomerMessageResponse, error)
	ChatbotMessage(ctx context.Context, in *ChatbotMessageRequest, opts ...grpc.CallOption) (*ChatbotMessageResponse, error)
	PingTasksQueue(ctx context.Context, in *PingTasksQueueRequest, opts ...grpc.CallOption) (*PingTasksQueueResponse, error)
	CreateTaskMessage(ctx context.Context, in *CreateTaskMessageRequest, opts ...grpc.CallOption) (*CreateTaskMessageResponse, error)
	CompleteTaskMessage(ctx context.Context, in *CompleteTaskMessageRequest, opts ...grpc.CallOption) (*CompleteTaskMessageResponse, error)
}

type messageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageServiceClient(cc grpc.ClientConnInterface) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) PingApiMessage(ctx context.Context, in *PingApiMessageRequest, opts ...grpc.CallOption) (*PingApiMessageResponse, error) {
	out := new(PingApiMessageResponse)
	err := c.cc.Invoke(ctx, MessageService_PingApiMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) CustomerMessage(ctx context.Context, in *CustomerMessageRequest, opts ...grpc.CallOption) (*CustomerMessageResponse, error) {
	out := new(CustomerMessageResponse)
	err := c.cc.Invoke(ctx, MessageService_CustomerMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) ChatbotMessage(ctx context.Context, in *ChatbotMessageRequest, opts ...grpc.CallOption) (*ChatbotMessageResponse, error) {
	out := new(ChatbotMessageResponse)
	err := c.cc.Invoke(ctx, MessageService_ChatbotMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) PingTasksQueue(ctx context.Context, in *PingTasksQueueRequest, opts ...grpc.CallOption) (*PingTasksQueueResponse, error) {
	out := new(PingTasksQueueResponse)
	err := c.cc.Invoke(ctx, MessageService_PingTasksQueue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) CreateTaskMessage(ctx context.Context, in *CreateTaskMessageRequest, opts ...grpc.CallOption) (*CreateTaskMessageResponse, error) {
	out := new(CreateTaskMessageResponse)
	err := c.cc.Invoke(ctx, MessageService_CreateTaskMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) CompleteTaskMessage(ctx context.Context, in *CompleteTaskMessageRequest, opts ...grpc.CallOption) (*CompleteTaskMessageResponse, error) {
	out := new(CompleteTaskMessageResponse)
	err := c.cc.Invoke(ctx, MessageService_CompleteTaskMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServiceServer is the server API for MessageService service.
// All implementations must embed UnimplementedMessageServiceServer
// for forward compatibility
type MessageServiceServer interface {
	PingApiMessage(context.Context, *PingApiMessageRequest) (*PingApiMessageResponse, error)
	CustomerMessage(context.Context, *CustomerMessageRequest) (*CustomerMessageResponse, error)
	ChatbotMessage(context.Context, *ChatbotMessageRequest) (*ChatbotMessageResponse, error)
	PingTasksQueue(context.Context, *PingTasksQueueRequest) (*PingTasksQueueResponse, error)
	CreateTaskMessage(context.Context, *CreateTaskMessageRequest) (*CreateTaskMessageResponse, error)
	CompleteTaskMessage(context.Context, *CompleteTaskMessageRequest) (*CompleteTaskMessageResponse, error)
	mustEmbedUnimplementedMessageServiceServer()
}

// UnimplementedMessageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMessageServiceServer struct {
}

func (UnimplementedMessageServiceServer) PingApiMessage(context.Context, *PingApiMessageRequest) (*PingApiMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingApiMessage not implemented")
}
func (UnimplementedMessageServiceServer) CustomerMessage(context.Context, *CustomerMessageRequest) (*CustomerMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustomerMessage not implemented")
}
func (UnimplementedMessageServiceServer) ChatbotMessage(context.Context, *ChatbotMessageRequest) (*ChatbotMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChatbotMessage not implemented")
}
func (UnimplementedMessageServiceServer) PingTasksQueue(context.Context, *PingTasksQueueRequest) (*PingTasksQueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingTasksQueue not implemented")
}
func (UnimplementedMessageServiceServer) CreateTaskMessage(context.Context, *CreateTaskMessageRequest) (*CreateTaskMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTaskMessage not implemented")
}
func (UnimplementedMessageServiceServer) CompleteTaskMessage(context.Context, *CompleteTaskMessageRequest) (*CompleteTaskMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteTaskMessage not implemented")
}
func (UnimplementedMessageServiceServer) mustEmbedUnimplementedMessageServiceServer() {}

// UnsafeMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServiceServer will
// result in compilation errors.
type UnsafeMessageServiceServer interface {
	mustEmbedUnimplementedMessageServiceServer()
}

func RegisterMessageServiceServer(s grpc.ServiceRegistrar, srv MessageServiceServer) {
	s.RegisterService(&MessageService_ServiceDesc, srv)
}

func _MessageService_PingApiMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingApiMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).PingApiMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_PingApiMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).PingApiMessage(ctx, req.(*PingApiMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_CustomerMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).CustomerMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_CustomerMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).CustomerMessage(ctx, req.(*CustomerMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_ChatbotMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatbotMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).ChatbotMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_ChatbotMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).ChatbotMessage(ctx, req.(*ChatbotMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_PingTasksQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingTasksQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).PingTasksQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_PingTasksQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).PingTasksQueue(ctx, req.(*PingTasksQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_CreateTaskMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).CreateTaskMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_CreateTaskMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).CreateTaskMessage(ctx, req.(*CreateTaskMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_CompleteTaskMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteTaskMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).CompleteTaskMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_CompleteTaskMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).CompleteTaskMessage(ctx, req.(*CompleteTaskMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageService_ServiceDesc is the grpc.ServiceDesc for MessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PingApiMessage",
			Handler:    _MessageService_PingApiMessage_Handler,
		},
		{
			MethodName: "CustomerMessage",
			Handler:    _MessageService_CustomerMessage_Handler,
		},
		{
			MethodName: "ChatbotMessage",
			Handler:    _MessageService_ChatbotMessage_Handler,
		},
		{
			MethodName: "PingTasksQueue",
			Handler:    _MessageService_PingTasksQueue_Handler,
		},
		{
			MethodName: "CreateTaskMessage",
			Handler:    _MessageService_CreateTaskMessage_Handler,
		},
		{
			MethodName: "CompleteTaskMessage",
			Handler:    _MessageService_CompleteTaskMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc-proto/message.proto",
}
