// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: grpc-proto/social.proto

package grpc_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SocialService_PingApiSocial_FullMethodName                     = "/social.SocialService/PingApiSocial"
	SocialService_PostCreate_FullMethodName                        = "/social.SocialService/PostCreate"
	SocialService_PostsFetchByUserID_FullMethodName                = "/social.SocialService/PostsFetchByUserID"
	SocialService_PostDelete_FullMethodName                        = "/social.SocialService/PostDelete"
	SocialService_PostsFetchVirtualLatest_FullMethodName           = "/social.SocialService/PostsFetchVirtualLatest"
	SocialService_PostsFetchVirtualByKeywordsLatest_FullMethodName = "/social.SocialService/PostsFetchVirtualByKeywordsLatest"
	SocialService_PostsFetchByKeyword_FullMethodName               = "/social.SocialService/PostsFetchByKeyword"
	SocialService_PostsFetchByKeywords_FullMethodName              = "/social.SocialService/PostsFetchByKeywords"
	SocialService_PostsFetchAllKeywords_FullMethodName             = "/social.SocialService/PostsFetchAllKeywords"
	SocialService_PostToggleLike_FullMethodName                    = "/social.SocialService/PostToggleLike"
	SocialService_PostFetchLikes_FullMethodName                    = "/social.SocialService/PostFetchLikes"
	SocialService_PostFetchViews_FullMethodName                    = "/social.SocialService/PostFetchViews"
	SocialService_PostCommentCreate_FullMethodName                 = "/social.SocialService/PostCommentCreate"
	SocialService_PostCommentsFetch_FullMethodName                 = "/social.SocialService/PostCommentsFetch"
	SocialService_PostCommentDelete_FullMethodName                 = "/social.SocialService/PostCommentDelete"
	SocialService_FollowCreate_FullMethodName                      = "/social.SocialService/FollowCreate"
	SocialService_FollowDelete_FullMethodName                      = "/social.SocialService/FollowDelete"
	SocialService_FollowingsFetch_FullMethodName                   = "/social.SocialService/FollowingsFetch"
	SocialService_FollowersFetch_FullMethodName                    = "/social.SocialService/FollowersFetch"
	SocialService_FollowsCounterFetch_FullMethodName               = "/social.SocialService/FollowsCounterFetch"
	SocialService_ProfileLikeCreate_FullMethodName                 = "/social.SocialService/ProfileLikeCreate"
	SocialService_ProfileLikeDelete_FullMethodName                 = "/social.SocialService/ProfileLikeDelete"
	SocialService_ProfileLikeGet_FullMethodName                    = "/social.SocialService/ProfileLikeGet"
)

// SocialServiceClient is the client API for SocialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SocialServiceClient interface {
	PingApiSocial(ctx context.Context, in *PingApiSocialRequest, opts ...grpc.CallOption) (*PingApiSocialResponse, error)
	PostCreate(ctx context.Context, in *PostCreateRequest, opts ...grpc.CallOption) (*PostCreateResponse, error)
	PostsFetchByUserID(ctx context.Context, in *PostsFetchByUserIDRequest, opts ...grpc.CallOption) (*PostsFetchByUserIDResponse, error)
	PostDelete(ctx context.Context, in *PostDeleteRequest, opts ...grpc.CallOption) (*PostDeleteResponse, error)
	PostsFetchVirtualLatest(ctx context.Context, in *PostsFetchVirtualLatestRequest, opts ...grpc.CallOption) (*PostsFetchVirtualLatestResponse, error)
	PostsFetchVirtualByKeywordsLatest(ctx context.Context, in *PostsFetchVirtualByKeywordsLatestRequest, opts ...grpc.CallOption) (*PostsFetchVirtualByKeywordsLatestResponse, error)
	PostsFetchByKeyword(ctx context.Context, in *PostsFetchByKeywordRequest, opts ...grpc.CallOption) (*PostsFetchByKeywordResponse, error)
	PostsFetchByKeywords(ctx context.Context, in *PostsFetchByKeywordsRequest, opts ...grpc.CallOption) (*PostsFetchByKeywordsResponse, error)
	PostsFetchAllKeywords(ctx context.Context, in *PostsFetchAllKeywordsRequest, opts ...grpc.CallOption) (*PostsFetchAllKeywordsResponse, error)
	PostToggleLike(ctx context.Context, in *PostToggleLikeRequest, opts ...grpc.CallOption) (*PostToggleLikeResponse, error)
	PostFetchLikes(ctx context.Context, in *PostFetchLikesRequest, opts ...grpc.CallOption) (*PostFetchLikesResponse, error)
	PostFetchViews(ctx context.Context, in *PostFetchViewsRequest, opts ...grpc.CallOption) (*PostFetchViewsResponse, error)
	PostCommentCreate(ctx context.Context, in *PostCommentCreateRequest, opts ...grpc.CallOption) (*PostCommentCreateResponse, error)
	PostCommentsFetch(ctx context.Context, in *PostCommentsFetchRequest, opts ...grpc.CallOption) (*PostCommentsFetchResponse, error)
	PostCommentDelete(ctx context.Context, in *PostCommentDeleteRequest, opts ...grpc.CallOption) (*PostCommentDeleteResponse, error)
	FollowCreate(ctx context.Context, in *FollowCreateRequest, opts ...grpc.CallOption) (*FollowCreateResponse, error)
	FollowDelete(ctx context.Context, in *FollowDeleteRequest, opts ...grpc.CallOption) (*FollowDeleteResponse, error)
	FollowingsFetch(ctx context.Context, in *FollowingsFetchRequest, opts ...grpc.CallOption) (*FollowingsFetchResponse, error)
	FollowersFetch(ctx context.Context, in *FollowersFetchRequest, opts ...grpc.CallOption) (*FollowersFetchResponse, error)
	FollowsCounterFetch(ctx context.Context, in *FollowsCounterFetchRequest, opts ...grpc.CallOption) (*FollowsCounterFetchResponse, error)
	ProfileLikeCreate(ctx context.Context, in *ProfileLikeCreateRequest, opts ...grpc.CallOption) (*ProfileLikeCreateResponse, error)
	ProfileLikeDelete(ctx context.Context, in *ProfileLikeDeleteRequest, opts ...grpc.CallOption) (*ProfileLikeDeleteResponse, error)
	ProfileLikeGet(ctx context.Context, in *ProfileLikeGetRequest, opts ...grpc.CallOption) (*ProfileLikeGetResponse, error)
}

type socialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSocialServiceClient(cc grpc.ClientConnInterface) SocialServiceClient {
	return &socialServiceClient{cc}
}

func (c *socialServiceClient) PingApiSocial(ctx context.Context, in *PingApiSocialRequest, opts ...grpc.CallOption) (*PingApiSocialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingApiSocialResponse)
	err := c.cc.Invoke(ctx, SocialService_PingApiSocial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) PostCreate(ctx context.Context, in *PostCreateRequest, opts ...grpc.CallOption) (*PostCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostCreateResponse)
	err := c.cc.Invoke(ctx, SocialService_PostCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) PostsFetchByUserID(ctx context.Context, in *PostsFetchByUserIDRequest, opts ...grpc.CallOption) (*PostsFetchByUserIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostsFetchByUserIDResponse)
	err := c.cc.Invoke(ctx, SocialService_PostsFetchByUserID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) PostDelete(ctx context.Context, in *PostDeleteRequest, opts ...grpc.CallOption) (*PostDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostDeleteResponse)
	err := c.cc.Invoke(ctx, SocialService_PostDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) PostsFetchVirtualLatest(ctx context.Context, in *PostsFetchVirtualLatestRequest, opts ...grpc.CallOption) (*PostsFetchVirtualLatestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostsFetchVirtualLatestResponse)
	err := c.cc.Invoke(ctx, SocialService_PostsFetchVirtualLatest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) PostsFetchVirtualByKeywordsLatest(ctx context.Context, in *PostsFetchVirtualByKeywordsLatestRequest, opts ...grpc.CallOption) (*PostsFetchVirtualByKeywordsLatestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostsFetchVirtualByKeywordsLatestResponse)
	err := c.cc.Invoke(ctx, SocialService_PostsFetchVirtualByKeywordsLatest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) PostsFetchByKeyword(ctx context.Context, in *PostsFetchByKeywordRequest, opts ...grpc.CallOption) (*PostsFetchByKeywordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostsFetchByKeywordResponse)
	err := c.cc.Invoke(ctx, SocialService_PostsFetchByKeyword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) PostsFetchByKeywords(ctx context.Context, in *PostsFetchByKeywordsRequest, opts ...grpc.CallOption) (*PostsFetchByKeywordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostsFetchByKeywordsResponse)
	err := c.cc.Invoke(ctx, SocialService_PostsFetchByKeywords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) PostsFetchAllKeywords(ctx context.Context, in *PostsFetchAllKeywordsRequest, opts ...grpc.CallOption) (*PostsFetchAllKeywordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostsFetchAllKeywordsResponse)
	err := c.cc.Invoke(ctx, SocialService_PostsFetchAllKeywords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) PostToggleLike(ctx context.Context, in *PostToggleLikeRequest, opts ...grpc.CallOption) (*PostToggleLikeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostToggleLikeResponse)
	err := c.cc.Invoke(ctx, SocialService_PostToggleLike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) PostFetchLikes(ctx context.Context, in *PostFetchLikesRequest, opts ...grpc.CallOption) (*PostFetchLikesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostFetchLikesResponse)
	err := c.cc.Invoke(ctx, SocialService_PostFetchLikes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) PostFetchViews(ctx context.Context, in *PostFetchViewsRequest, opts ...grpc.CallOption) (*PostFetchViewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostFetchViewsResponse)
	err := c.cc.Invoke(ctx, SocialService_PostFetchViews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) PostCommentCreate(ctx context.Context, in *PostCommentCreateRequest, opts ...grpc.CallOption) (*PostCommentCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostCommentCreateResponse)
	err := c.cc.Invoke(ctx, SocialService_PostCommentCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) PostCommentsFetch(ctx context.Context, in *PostCommentsFetchRequest, opts ...grpc.CallOption) (*PostCommentsFetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostCommentsFetchResponse)
	err := c.cc.Invoke(ctx, SocialService_PostCommentsFetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) PostCommentDelete(ctx context.Context, in *PostCommentDeleteRequest, opts ...grpc.CallOption) (*PostCommentDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostCommentDeleteResponse)
	err := c.cc.Invoke(ctx, SocialService_PostCommentDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) FollowCreate(ctx context.Context, in *FollowCreateRequest, opts ...grpc.CallOption) (*FollowCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowCreateResponse)
	err := c.cc.Invoke(ctx, SocialService_FollowCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) FollowDelete(ctx context.Context, in *FollowDeleteRequest, opts ...grpc.CallOption) (*FollowDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowDeleteResponse)
	err := c.cc.Invoke(ctx, SocialService_FollowDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) FollowingsFetch(ctx context.Context, in *FollowingsFetchRequest, opts ...grpc.CallOption) (*FollowingsFetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowingsFetchResponse)
	err := c.cc.Invoke(ctx, SocialService_FollowingsFetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) FollowersFetch(ctx context.Context, in *FollowersFetchRequest, opts ...grpc.CallOption) (*FollowersFetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowersFetchResponse)
	err := c.cc.Invoke(ctx, SocialService_FollowersFetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) FollowsCounterFetch(ctx context.Context, in *FollowsCounterFetchRequest, opts ...grpc.CallOption) (*FollowsCounterFetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowsCounterFetchResponse)
	err := c.cc.Invoke(ctx, SocialService_FollowsCounterFetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) ProfileLikeCreate(ctx context.Context, in *ProfileLikeCreateRequest, opts ...grpc.CallOption) (*ProfileLikeCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileLikeCreateResponse)
	err := c.cc.Invoke(ctx, SocialService_ProfileLikeCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) ProfileLikeDelete(ctx context.Context, in *ProfileLikeDeleteRequest, opts ...grpc.CallOption) (*ProfileLikeDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileLikeDeleteResponse)
	err := c.cc.Invoke(ctx, SocialService_ProfileLikeDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) ProfileLikeGet(ctx context.Context, in *ProfileLikeGetRequest, opts ...grpc.CallOption) (*ProfileLikeGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileLikeGetResponse)
	err := c.cc.Invoke(ctx, SocialService_ProfileLikeGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SocialServiceServer is the server API for SocialService service.
// All implementations must embed UnimplementedSocialServiceServer
// for forward compatibility.
type SocialServiceServer interface {
	PingApiSocial(context.Context, *PingApiSocialRequest) (*PingApiSocialResponse, error)
	PostCreate(context.Context, *PostCreateRequest) (*PostCreateResponse, error)
	PostsFetchByUserID(context.Context, *PostsFetchByUserIDRequest) (*PostsFetchByUserIDResponse, error)
	PostDelete(context.Context, *PostDeleteRequest) (*PostDeleteResponse, error)
	PostsFetchVirtualLatest(context.Context, *PostsFetchVirtualLatestRequest) (*PostsFetchVirtualLatestResponse, error)
	PostsFetchVirtualByKeywordsLatest(context.Context, *PostsFetchVirtualByKeywordsLatestRequest) (*PostsFetchVirtualByKeywordsLatestResponse, error)
	PostsFetchByKeyword(context.Context, *PostsFetchByKeywordRequest) (*PostsFetchByKeywordResponse, error)
	PostsFetchByKeywords(context.Context, *PostsFetchByKeywordsRequest) (*PostsFetchByKeywordsResponse, error)
	PostsFetchAllKeywords(context.Context, *PostsFetchAllKeywordsRequest) (*PostsFetchAllKeywordsResponse, error)
	PostToggleLike(context.Context, *PostToggleLikeRequest) (*PostToggleLikeResponse, error)
	PostFetchLikes(context.Context, *PostFetchLikesRequest) (*PostFetchLikesResponse, error)
	PostFetchViews(context.Context, *PostFetchViewsRequest) (*PostFetchViewsResponse, error)
	PostCommentCreate(context.Context, *PostCommentCreateRequest) (*PostCommentCreateResponse, error)
	PostCommentsFetch(context.Context, *PostCommentsFetchRequest) (*PostCommentsFetchResponse, error)
	PostCommentDelete(context.Context, *PostCommentDeleteRequest) (*PostCommentDeleteResponse, error)
	FollowCreate(context.Context, *FollowCreateRequest) (*FollowCreateResponse, error)
	FollowDelete(context.Context, *FollowDeleteRequest) (*FollowDeleteResponse, error)
	FollowingsFetch(context.Context, *FollowingsFetchRequest) (*FollowingsFetchResponse, error)
	FollowersFetch(context.Context, *FollowersFetchRequest) (*FollowersFetchResponse, error)
	FollowsCounterFetch(context.Context, *FollowsCounterFetchRequest) (*FollowsCounterFetchResponse, error)
	ProfileLikeCreate(context.Context, *ProfileLikeCreateRequest) (*ProfileLikeCreateResponse, error)
	ProfileLikeDelete(context.Context, *ProfileLikeDeleteRequest) (*ProfileLikeDeleteResponse, error)
	ProfileLikeGet(context.Context, *ProfileLikeGetRequest) (*ProfileLikeGetResponse, error)
	mustEmbedUnimplementedSocialServiceServer()
}

// UnimplementedSocialServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSocialServiceServer struct{}

func (UnimplementedSocialServiceServer) PingApiSocial(context.Context, *PingApiSocialRequest) (*PingApiSocialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingApiSocial not implemented")
}
func (UnimplementedSocialServiceServer) PostCreate(context.Context, *PostCreateRequest) (*PostCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostCreate not implemented")
}
func (UnimplementedSocialServiceServer) PostsFetchByUserID(context.Context, *PostsFetchByUserIDRequest) (*PostsFetchByUserIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostsFetchByUserID not implemented")
}
func (UnimplementedSocialServiceServer) PostDelete(context.Context, *PostDeleteRequest) (*PostDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostDelete not implemented")
}
func (UnimplementedSocialServiceServer) PostsFetchVirtualLatest(context.Context, *PostsFetchVirtualLatestRequest) (*PostsFetchVirtualLatestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostsFetchVirtualLatest not implemented")
}
func (UnimplementedSocialServiceServer) PostsFetchVirtualByKeywordsLatest(context.Context, *PostsFetchVirtualByKeywordsLatestRequest) (*PostsFetchVirtualByKeywordsLatestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostsFetchVirtualByKeywordsLatest not implemented")
}
func (UnimplementedSocialServiceServer) PostsFetchByKeyword(context.Context, *PostsFetchByKeywordRequest) (*PostsFetchByKeywordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostsFetchByKeyword not implemented")
}
func (UnimplementedSocialServiceServer) PostsFetchByKeywords(context.Context, *PostsFetchByKeywordsRequest) (*PostsFetchByKeywordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostsFetchByKeywords not implemented")
}
func (UnimplementedSocialServiceServer) PostsFetchAllKeywords(context.Context, *PostsFetchAllKeywordsRequest) (*PostsFetchAllKeywordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostsFetchAllKeywords not implemented")
}
func (UnimplementedSocialServiceServer) PostToggleLike(context.Context, *PostToggleLikeRequest) (*PostToggleLikeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostToggleLike not implemented")
}
func (UnimplementedSocialServiceServer) PostFetchLikes(context.Context, *PostFetchLikesRequest) (*PostFetchLikesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostFetchLikes not implemented")
}
func (UnimplementedSocialServiceServer) PostFetchViews(context.Context, *PostFetchViewsRequest) (*PostFetchViewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostFetchViews not implemented")
}
func (UnimplementedSocialServiceServer) PostCommentCreate(context.Context, *PostCommentCreateRequest) (*PostCommentCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostCommentCreate not implemented")
}
func (UnimplementedSocialServiceServer) PostCommentsFetch(context.Context, *PostCommentsFetchRequest) (*PostCommentsFetchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostCommentsFetch not implemented")
}
func (UnimplementedSocialServiceServer) PostCommentDelete(context.Context, *PostCommentDeleteRequest) (*PostCommentDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostCommentDelete not implemented")
}
func (UnimplementedSocialServiceServer) FollowCreate(context.Context, *FollowCreateRequest) (*FollowCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FollowCreate not implemented")
}
func (UnimplementedSocialServiceServer) FollowDelete(context.Context, *FollowDeleteRequest) (*FollowDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FollowDelete not implemented")
}
func (UnimplementedSocialServiceServer) FollowingsFetch(context.Context, *FollowingsFetchRequest) (*FollowingsFetchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FollowingsFetch not implemented")
}
func (UnimplementedSocialServiceServer) FollowersFetch(context.Context, *FollowersFetchRequest) (*FollowersFetchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FollowersFetch not implemented")
}
func (UnimplementedSocialServiceServer) FollowsCounterFetch(context.Context, *FollowsCounterFetchRequest) (*FollowsCounterFetchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FollowsCounterFetch not implemented")
}
func (UnimplementedSocialServiceServer) ProfileLikeCreate(context.Context, *ProfileLikeCreateRequest) (*ProfileLikeCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProfileLikeCreate not implemented")
}
func (UnimplementedSocialServiceServer) ProfileLikeDelete(context.Context, *ProfileLikeDeleteRequest) (*ProfileLikeDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProfileLikeDelete not implemented")
}
func (UnimplementedSocialServiceServer) ProfileLikeGet(context.Context, *ProfileLikeGetRequest) (*ProfileLikeGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProfileLikeGet not implemented")
}
func (UnimplementedSocialServiceServer) mustEmbedUnimplementedSocialServiceServer() {}
func (UnimplementedSocialServiceServer) testEmbeddedByValue()                       {}

// UnsafeSocialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SocialServiceServer will
// result in compilation errors.
type UnsafeSocialServiceServer interface {
	mustEmbedUnimplementedSocialServiceServer()
}

func RegisterSocialServiceServer(s grpc.ServiceRegistrar, srv SocialServiceServer) {
	// If the following call pancis, it indicates UnimplementedSocialServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SocialService_ServiceDesc, srv)
}

func _SocialService_PingApiSocial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingApiSocialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).PingApiSocial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_PingApiSocial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).PingApiSocial(ctx, req.(*PingApiSocialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_PostCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).PostCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_PostCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).PostCreate(ctx, req.(*PostCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_PostsFetchByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostsFetchByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).PostsFetchByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_PostsFetchByUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).PostsFetchByUserID(ctx, req.(*PostsFetchByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_PostDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).PostDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_PostDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).PostDelete(ctx, req.(*PostDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_PostsFetchVirtualLatest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostsFetchVirtualLatestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).PostsFetchVirtualLatest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_PostsFetchVirtualLatest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).PostsFetchVirtualLatest(ctx, req.(*PostsFetchVirtualLatestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_PostsFetchVirtualByKeywordsLatest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostsFetchVirtualByKeywordsLatestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).PostsFetchVirtualByKeywordsLatest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_PostsFetchVirtualByKeywordsLatest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).PostsFetchVirtualByKeywordsLatest(ctx, req.(*PostsFetchVirtualByKeywordsLatestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_PostsFetchByKeyword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostsFetchByKeywordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).PostsFetchByKeyword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_PostsFetchByKeyword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).PostsFetchByKeyword(ctx, req.(*PostsFetchByKeywordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_PostsFetchByKeywords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostsFetchByKeywordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).PostsFetchByKeywords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_PostsFetchByKeywords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).PostsFetchByKeywords(ctx, req.(*PostsFetchByKeywordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_PostsFetchAllKeywords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostsFetchAllKeywordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).PostsFetchAllKeywords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_PostsFetchAllKeywords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).PostsFetchAllKeywords(ctx, req.(*PostsFetchAllKeywordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_PostToggleLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostToggleLikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).PostToggleLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_PostToggleLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).PostToggleLike(ctx, req.(*PostToggleLikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_PostFetchLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostFetchLikesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).PostFetchLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_PostFetchLikes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).PostFetchLikes(ctx, req.(*PostFetchLikesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_PostFetchViews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostFetchViewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).PostFetchViews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_PostFetchViews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).PostFetchViews(ctx, req.(*PostFetchViewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_PostCommentCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostCommentCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).PostCommentCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_PostCommentCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).PostCommentCreate(ctx, req.(*PostCommentCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_PostCommentsFetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostCommentsFetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).PostCommentsFetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_PostCommentsFetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).PostCommentsFetch(ctx, req.(*PostCommentsFetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_PostCommentDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostCommentDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).PostCommentDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_PostCommentDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).PostCommentDelete(ctx, req.(*PostCommentDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_FollowCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).FollowCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_FollowCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).FollowCreate(ctx, req.(*FollowCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_FollowDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).FollowDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_FollowDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).FollowDelete(ctx, req.(*FollowDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_FollowingsFetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowingsFetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).FollowingsFetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_FollowingsFetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).FollowingsFetch(ctx, req.(*FollowingsFetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_FollowersFetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowersFetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).FollowersFetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_FollowersFetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).FollowersFetch(ctx, req.(*FollowersFetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_FollowsCounterFetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowsCounterFetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).FollowsCounterFetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_FollowsCounterFetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).FollowsCounterFetch(ctx, req.(*FollowsCounterFetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_ProfileLikeCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileLikeCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).ProfileLikeCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_ProfileLikeCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).ProfileLikeCreate(ctx, req.(*ProfileLikeCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_ProfileLikeDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileLikeDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).ProfileLikeDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_ProfileLikeDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).ProfileLikeDelete(ctx, req.(*ProfileLikeDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_ProfileLikeGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileLikeGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).ProfileLikeGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_ProfileLikeGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).ProfileLikeGet(ctx, req.(*ProfileLikeGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SocialService_ServiceDesc is the grpc.ServiceDesc for SocialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SocialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "social.SocialService",
	HandlerType: (*SocialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PingApiSocial",
			Handler:    _SocialService_PingApiSocial_Handler,
		},
		{
			MethodName: "PostCreate",
			Handler:    _SocialService_PostCreate_Handler,
		},
		{
			MethodName: "PostsFetchByUserID",
			Handler:    _SocialService_PostsFetchByUserID_Handler,
		},
		{
			MethodName: "PostDelete",
			Handler:    _SocialService_PostDelete_Handler,
		},
		{
			MethodName: "PostsFetchVirtualLatest",
			Handler:    _SocialService_PostsFetchVirtualLatest_Handler,
		},
		{
			MethodName: "PostsFetchVirtualByKeywordsLatest",
			Handler:    _SocialService_PostsFetchVirtualByKeywordsLatest_Handler,
		},
		{
			MethodName: "PostsFetchByKeyword",
			Handler:    _SocialService_PostsFetchByKeyword_Handler,
		},
		{
			MethodName: "PostsFetchByKeywords",
			Handler:    _SocialService_PostsFetchByKeywords_Handler,
		},
		{
			MethodName: "PostsFetchAllKeywords",
			Handler:    _SocialService_PostsFetchAllKeywords_Handler,
		},
		{
			MethodName: "PostToggleLike",
			Handler:    _SocialService_PostToggleLike_Handler,
		},
		{
			MethodName: "PostFetchLikes",
			Handler:    _SocialService_PostFetchLikes_Handler,
		},
		{
			MethodName: "PostFetchViews",
			Handler:    _SocialService_PostFetchViews_Handler,
		},
		{
			MethodName: "PostCommentCreate",
			Handler:    _SocialService_PostCommentCreate_Handler,
		},
		{
			MethodName: "PostCommentsFetch",
			Handler:    _SocialService_PostCommentsFetch_Handler,
		},
		{
			MethodName: "PostCommentDelete",
			Handler:    _SocialService_PostCommentDelete_Handler,
		},
		{
			MethodName: "FollowCreate",
			Handler:    _SocialService_FollowCreate_Handler,
		},
		{
			MethodName: "FollowDelete",
			Handler:    _SocialService_FollowDelete_Handler,
		},
		{
			MethodName: "FollowingsFetch",
			Handler:    _SocialService_FollowingsFetch_Handler,
		},
		{
			MethodName: "FollowersFetch",
			Handler:    _SocialService_FollowersFetch_Handler,
		},
		{
			MethodName: "FollowsCounterFetch",
			Handler:    _SocialService_FollowsCounterFetch_Handler,
		},
		{
			MethodName: "ProfileLikeCreate",
			Handler:    _SocialService_ProfileLikeCreate_Handler,
		},
		{
			MethodName: "ProfileLikeDelete",
			Handler:    _SocialService_ProfileLikeDelete_Handler,
		},
		{
			MethodName: "ProfileLikeGet",
			Handler:    _SocialService_ProfileLikeGet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc-proto/social.proto",
}
